"use client";

import React, { useEffect, useState } from "react";
import CountUp from "react-countup";
import { CircularProgressbar, buildStyles } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";

const DashboardOverview = () => {
  const totalBudget = 10000;
  const totalExpenses = 7200;
  const usagePercent = (totalExpenses / totalBudget) * 100;
  const isOverBudget = totalExpenses > totalBudget;

  // 🧠 Fix: Random tip only after hydration
  const tips = [
    "Track small daily expenses — they add up!",
    "Use the 50/30/20 rule to balance spending.",
    "Cancel unused subscriptions monthly.",
    "Review your budgets weekly for better control.",
    "Automate savings — out of sight, out of spend!",
  ];

  const [tipOfTheDay, setTipOfTheDay] = useState("");
  const financeFacts = [
  "You could save ₹36,500/year by cutting one ₹100 chai a day!",
  "India’s inflation rate in 2024 was 4.7%.",
  "Only 24% of Indians have a personal budget.",
  "Emergency funds should cover at least 3 months of expenses.",
  "Spending ₹500/month on subscriptions = ₹6,000/year!",
];

const [factOfTheMoment, setFactOfTheMoment] = useState("");

useEffect(() => {
  const randomIndex = Math.floor(Math.random() * financeFacts.length);
  setFactOfTheMoment(financeFacts[randomIndex]);
}, []);


  useEffect(() => {
    const randomIndex = Math.floor(Math.random() * tips.length);
    setTipOfTheDay(tips[randomIndex]);
  }, []);

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6">
    {/* Finance Facts Card */}
<div className="bg-white shadow-md rounded-xl p-5 border space-y-3 flex flex-col justify-between">
  <h2 className="text-xl font-semibold text-gray-800">💡 Did You Know?</h2>
  <p className="text-gray-600 text-sm leading-relaxed">
    {factOfTheMoment}
  </p>
  <span className="text-xs text-gray-400">Powered by PennyPath Insights</span>
</div>




      {/* Tip of the Day */}
      <div className="bg-white shadow-md rounded-xl p-5 border space-y-3 flex flex-col justify-between">
        <h2 className="text-xl font-semibold text-gray-800">🤖 Tip of the Day</h2>
        {tipOfTheDay ? (
          <>
            <p className="text-gray-600 text-sm leading-relaxed">{tipOfTheDay}</p>
            <span className="text-xs text-gray-400">Generated by PennyPath AI</span>
          </>
        ) : (
          <div className="text-sm text-gray-400">Loading tip...</div>
        )}
      </div>
    </div>
  );
};

export default DashboardOverview;
